Vagrant.configure("2") do |config|
  (1..1).each do |i| 
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = "bento/ubuntu-16.04"
      subconfig.vm.provision :shell, path: "bootstrap.sh", args: "#{i}"
    end
  end
 
end
